name: Install MbedOS

on:
  workflow_dispatch:
  
jobs:
  install:
    runs-on: ubuntu-latest
    
    steps:
      - name: install MbedOS
        run: |
          python3 -m pip install mbed-cli
          mbed --help
          
  
