name: Install MbedOS

on:
  workflow_dispatch:
  
jobs:
  install:
    runs-on: ubuntu-latest
    
    steps:
      - name: Install Arduino-CLI
        uses: arduino/setup-arduino-cli@v1.1.1
        
      - name: Install the platform
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:mbed
          
      - name: install MbedOS
        run: |
          python3 -m pip install mbed-cli
       
      - name: Configure mbed
        run: |
          arduino-cli config dump -v
          ls -l /opt/hostedtoolcache
          ls -l /opt
          ls -lR `which arduino-cli`
          ls -lR /opt/hostedtoolcache/arduino-cli
        
  
